"""column revoke add in refresh  token table

Revision ID: 24a19efd00c5
Revises: 1058cb7f9707
Create Date: 2026-09-09 18:45:22.011255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '24a19efd00c5'
down_revision: Union[str, Sequence[str], None] = '1058cb7f9707'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('revoked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'revoked')
    # ### end Alembic commands ###
